import type { Metadata } from "next";
import { Inter } from "next/font/google";


import "./globals.css";
import { MyProvider } from "@/app/MyContext";

const inter = Inter({
  subsets: ["latin", "vietnamese"], // quan trọng!
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <MyProvider>
        {children}
        </MyProvider>
      </body>
    </html>
  );
}
