
export const tinhThanh = () => {
  return [
    {"value":"Long Xuyên",
     "label": "Thành phố Long Xuyên, An Giang"},
    {"value":"Bà Rịa",
     "label": "Thành phố Bà Rịa, Bà Rịa - Vũng Tàu"},
     {"value":"Bạc Liêu",
     "label": "Thành phố Bạc Liêu, Bạc Liêu"},
     {"value":"Bắc Giang",
     "label": "Thành phố Bắc Giang,Bắc Giang"},
    {"value":"Bắc Kạn",
     "label": "Thành phố Bắc Kạn, Bắc Kạn"},
    {"value":"Bắc Ninh",
     "label": "Thành phố Bắc Ninh, Bắc Ninh"},
    {"value":"Bến Tre",
     "label": "Thành phố Bến Tre, Bến Tre"},
    {"value":"Thủ Dầu Một",
     "label": "Thành phố Thủ Dầu Một, Bình Dương"},
    {"value":"Quy Nhơn",
     "label": "Thành phố Quy Nhơn, Bình Định"},
    {"value":"Đồng Xoài",
     "label": "Thành phố Đồng Xoài, Bình Phước"},
    {"value":"Phan Thiết",
     "label": "Thành phố Phan Thiết, Bình Thuận"},
    {"value":"Cà Mau",
     "label": "Thành phố Cà Mau, Cà Mau"},
     {"value":"Cao Bằng",
     "label": "Thành phố Cao Bằng, Cao Bằng"},
     {"value":"Ninh Kiều",
     "label": "Quận Ninh Kiều, Cần Thơ"},
     {"value":"Buôn Ma Thuột",
     "label": "Thành phố Buôn Ma Thuột, Đắk Lắk"},
     {"value":"Điện Biên Phủ",
     "label": "Thành phố Điện Biên Phủ, Điện Biên"},
     {"value":"Biên Hòa",
     "label": "Thành phố Biên Hòa, Đồng Nai"},
     {"value":"Cao Lãnh",
     "label": "Thành phố Cao Lãnh, Đồng Tháp"},
     {"value":"Pleiku",
     "label": "Thành phố Pleiku ,Gia Lai"},
     {"value":"Hà Giang",
     "label": "Thành phố Hà Giang, Hà Giang"},
     {"value":"Phủ Lý",
     "label": "Thành phố Phủ Lý, Hà Nam"},
     {"value":"Hà Nội",
     "label": "Thủ đô Hà Nội"},
     {"value":"Hà Tĩnh",
     "label": "Thành phố Hà Tĩnh, Hà Tĩnh"},
     {"value":"Thành phố Hải Dương",
     "label": "Thành phố Hải Dương, Hải Dương"},
     {"value":"Hải Phòng",
     "label": "Hải Phòng"},
     {"value":"Hòa Bình",
     "label": "Thành phố Hòa Bình, Hòa Bình"},
     {"value":"Thành phố Hồ Chí Minh",
     "label": "Thành phố Hồ Chí Minh"},
     {"value":"Quận 1",
     "label": "Quận 1, Thành Phố Hồ Chí Minh"},
     {"value":"Hưng Yên",
     "label": "Thành phố Hưng Yên, Hưng Yên"},
     {"value":"Nha Trang",
     "label": "Thành phố Nha Trang, Khánh Hòa"},
     {"value":"Rạch Giá",
     "label": "Thành phố Rạch Giá, Kiên Giang"},
     {"value":"Kon Tum",
     "label": "Thành phố Kon Tum, Kon Tum"},
     {"value":"Lai Châu",
     "label": "Thành phố Lai Châu, Lai Châu"},
     {"value":"Lạng Sơn",
     "label": "Thành phố Lạng Sơn, Lạng Sơn"},
     {"value":"Lào Cai",
     "label": "Thành phố Lào Cai, Lào Cai"},
     {"value":"Đà Lạt",
     "label": "Thành phố Đà Lạt, Lâm Đồng"},
     {"value":"Tân An",
     "label": "Thành phố Tân An, Long An"},
     {"value":"Nam Định",
     "label": "Thành phố Nam Định, Nam Định"},
     {"value":"Vinh",
     "label": "Thành phố Vinh, Nghệ An"},
     {"value":"Ninh Bình",
     "label": "Thành phố Ninh Bình, Ninh Bình"},
     {"value":"Việt Trì",
     "label": "Thành phố Việt Trì, Phú Thọ"},
     {"value":"Tuy Hòa",
     "label": "Thành phố Tuy Hòa, Phú Yên"},
     {"value":"Đồng Hới",
     "label": "Thành phố Đồng Hới, Quảng Bình"},
     {"value":"Tam Kỳ",
     "label": "Thành phố Tam Kỳ, Quảng Nam"},
     {"value":"Quảng Ngãi",
     "label": "Thành phố Quảng Ngãi, Quảng Ngãi"},
     {"value":"Hạ Long",
     "label": "Thành phố Hạ Long, Quảng Ninh"},
     {"value":"Đông Hà",
     "label": "Thành phố Đông Hà, Quảng Trị"},
     {"value":"Sóc Trăng",
     "label": "Thành phố Sóc Trăng, Sóc Trăng"},
     {"value":"Sơn La",
     "label": "Thành phố Sơn La, Sơn La"},
     {"value":"Tây Ninh",
     "label": "Thành phố Tây Ninh, Tây Ninh"},
     {"value":"Thái Bình",
     "label": "Thành phố Thái Bình, Thái Bình"},
     {"value":"Thái Nguyên",
     "label": "Thành phố Thái Nguyên, Thái Nguyên"},
     {"value":"Thanh Hóa",
     "label": "Thành phố Thanh Hóa, Thanh Hóa"},
     {"value":"Huế",
     "label": "Thành phố Huế, Thừa Thiên Huế"},
     {"value":"Mỹ Tho",
     "label": "Thành phố Mỹ Tho, Tiền Giang"},
     {"value":"Trà Vinh",
     "label": "Thành phố Trà Vinh, Trà Vinh"},
     {"value":"Tuyên Quang",
     "label": "Thành phố Tuyên Quang, Tuyên Quang"},
     {"value":"Vĩnh Long",
     "label": "Thành phố Vĩnh Long, Vĩnh Long"},
     {"value":"Vĩnh Yên",
     "label": "Thành phố Vĩnh Yên, Vĩnh Phúc"},
     {"value":"Yên Bái",
     "label": "Thành phố Yên Bái, Yên Bái"},
     {"value":"Cam Ranh",
     "label": "Thành phố Cam Ranh, Khánh Hòa"},
     {"value":"Châu Đốc",
     "label": "Thành phố Châu Đốc, An Giang"},
     {"value":"Hà Tiên",
     "label": "Thành phố Hà Tiên, Kiên Giang"},
     {"value":"Hội An",
     "label": "Thành phố Hội An, Quảng Nam"},
     {"value":"Phúc Yên",
     "label": "Thành phố Phúc Yên, Vĩnh Phúc"},
     {"value":"Sa Đéc",
     "label": "Thành phố Sa Đéc, Đồng Tháp"},
     {"value":"Sông Công",
     "label": "Thành phố Sông Công, Thái Nguyên"},
     {"value":"Tam Điệp",
     "label": "Thành phố Tam Điệp, Ninh Bình"},
     {"value":"Uông Bí",
     "label": "Thành phố Uông Bí, Quảng Ninh"},
     {"value":"Vũng Tàu",
     "label": "Thành phố Vũng Tàu, Bà Rịa - Vũng Tàu"},
     {"value":"Thuận An",
     "label": "Thành phố Thuận An, Bình Dương"},
     {"value":"Dĩ An",
     "label": "Thành phố Dĩ An, Bình Dương"},
     {"value":"Long Khánh",
     "label": "Thành phố Long Khánh, Đồng Nai"},
     {"value":"Quận 3",
     "label": "Quận 3, Thành phố Hồ Chí Minh"},
     {"value":"Quận 4",
     "label": "Quận 4, Thành phố Hồ Chí Minh"},
     {"value":"Quận 5",
     "label": "Quận 5, Thành phố Hồ Chí Minh"},
     {"value":"Quận 7",
     "label": "Quận 7, Thành phố Hồ Chí Minh"},
     {"value":"Quận 8",
     "label": "Quận 8, Thành phố Hồ Chí Minh"},
     {"value":"Quận 10",
     "label": "Quận 10, Thành phố Hồ Chí Minh"},
     {"value":"Quận 11",
     "label": "Quận 11, Thành phố Hồ Chí Minh"},
     {"value":"Quận 12",
     "label": "Quận 12, Thành phố Hồ Chí Minh"},
     {"value":"Tân Bình",
     "label": "Quận Tân Bình, Thành phố Hồ Chí Minh"},
     {"value":"Tân Phú",
     "label": "Quận Tân Phú, Thành phố Hồ Chí Minh"},
     {"value":"Bình Tân",
     "label": "Quận Bình Tân, Thành phố Hồ Chí Minh"},
     {"value":"Bình Thạnh",
     "label": "Quận Bình Thạnh, Thành phố Hồ Chí Minh"},
     {"value":"Gò Vấp",
     "label": "Quận Gò Vấp, Thành phố Hồ Chí Minh"},
     {"value":"Phú Nhuận",
     "label": "Quận Phú Nhuận, Thành phố Hồ Chí Minh"},
     {"value":"Thủ Đức",
     "label": "Thành phố Thủ đức, Thành phố Hồ Chí Minh"},
     {"value":"Hai Bà Trưng",
     "label": "Quận Hai Bà Trưng, Thủ đô Hà Nội"},
     {"value":"Thanh Xuân",
     "label": "Quận Thanh Xuân, Thủ đô Hà Nội"},
     {"value":"Long Biên",
     "label": "Quận Long Biên, Thủ đô Hà Nội"},
     {"value":"Hà Đông",
     "label": "Quận Hà Đông, Thủ đô Hà Nội"},
     {"value":"Bắc Từ Liêm",
     "label": "Quận Bắc Từ Liêm, Thủ đô Hà Nội"},
     {"value":"Cẩm Lệ",
     "label": "Quận Cẩm Lệ, Thành phố Đà Nẵng"},
     {"value":"Liên Chiểu",
     "label": "Quận Liên Chiểu, Thành phố Đà Nẵng"},
     {"value":"Hòa Vang",
     "label": "Quận Hòa Vang, Thành phố Đà Nẵng"},
     {"value":"Đà Nẵng",
     "label": "Thành phố Đà Nẵng"}
  ]
}

 
